---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyse_sense(analyse_sense)
	translate_definition(translate_definition)
	translate_all_lemmas(translate_all_lemmas)
	expand_synonyms(expand_synonyms)
	filter_synonyms(filter_synonyms)
	assemble_result(assemble_result)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyse_sense;
	analyse_sense --> translate_definition;
	expand_synonyms --> filter_synonyms;
	filter_synonyms --> assemble_result;
	translate_all_lemmas --> expand_synonyms;
	translate_definition --> translate_all_lemmas;
	assemble_result --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
